### ISSUE TITLE
Add aria-label to checkbox input

### ISSUE THREAD

**Issue by paologhidoni** [fac-23/preA-testing-raymiah#20]
https://github.com/fac-23/preA-testing-raymiah/blob/248e8825a7c1b09075b97f8a19cd7471f318b7b2/index.js#L25

Hey! The app looks great! We are trying hard to find something to suggest. 🌟

You could add the aria-label attribute to the checkbox input to explain what the checkbox does when an impaired user uses the screen reader, for example it could say something like "check the checkbox to mark this task as completed".

**Comment by raythompsonwebdev** [comment]
All done!.
