### ISSUE TITLE
Give delete button attribute type="button"

### ISSUE THREAD

**Issue by paologhidoni** [fac-23/preA-testing-raymiah#21]
https://github.com/fac-23/preA-testing-raymiah/blob/248e8825a7c1b09075b97f8a19cd7471f318b7b2/index.js#L42

Just guessing whether the delete button type attribute could be set as "button" instead of "submit" since it's not submitting anything? 

We don't know how to just write a comment without opening an Issue 😆 but we wanted to say that the use of the localStorage property is really cool! We will look it up!

**Comment by raythompsonwebdev** [comment]
Thanks!
