### ISSUE TITLE
Link validation messages to inputs

### ISSUE THREAD

**Issue by oliverjam** [fac-23/preA-testing-raymiah#24]
https://github.com/fac-23/preA-testing-raymiah/blob/248e8825a7c1b09075b97f8a19cd7471f318b7b2/index.html#L32

It's a good idea to connect an input to any extra information describing it inside other elements (like help text or validation/error messages). You can do this with the `aria-describedby` attribute—it takes the ID of another element that has additional info for the input.

**Comment by raythompsonwebdev** [comment]
All done!

**Comment by oliverjam** [comment]
Quick reminder that it's good practice to connect the commit/PR that resolves an issue. You can do this by adding `Relates #x` (where `x` is the issue number—in this case `24`) to the commit message or PR description. That way when the commit is pushed it'll automatically show up here. You can also use `Fix #x` to auto-close an issue if you're sure it is resolved by the commit.
