### ISSUE TITLE
Test for if items are correctly deleted or completed.

### ISSUE THREAD

**Issue by miahbates** [fac-23/preA-testing-raymiah#6]
Check the length of the section to see if it has been added to the right place. 

Completed - when you check the checkbox, will move to the completed section.
 
Deleted - when clicking the delete button item will be removed from the list.

**Comment by raythompsonwebdev** [comment]
basic test to check whether task has been added to list with text added done.
basic test to check whether item has been marked completed using checkbox done. 
basic test to check if item deleted done. 
function to delete items done and added.
basic CSS added.
